CREATE TABLE assinatura
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    preapproval_id VARCHAR(255),
    start_date     date,
    expiry_date    date,
    active         BOOLEAN                                 NOT NULL,
    tipo_plano     VARCHAR(255),
    status         VARCHAR(255),
    usuario_id     BIGINT,
    CONSTRAINT pk_assinatura PRIMARY KEY (id)
);

CREATE TABLE coupon
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code       VARCHAR(255)                            NOT NULL,
    discount   DOUBLE PRECISION                        NOT NULL,
    percentage BOOLEAN                                 NOT NULL,
    active     BOOLEAN                                 NOT NULL,
    owner_id   BIGINT,
    CONSTRAINT pk_coupon PRIMARY KEY (id)
);

CREATE TABLE coupon_usage
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    coupon_id BIGINT                                  NOT NULL,
    user_id   BIGINT                                  NOT NULL,
    used_at   TIMESTAMP,
    CONSTRAINT pk_couponusage PRIMARY KEY (id)
);

CREATE TABLE participante
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id   BIGINT,
    ranked_id BIGINT,
    pontuacao INT                                     NOT NULL,
    CONSTRAINT pk_participante PRIMARY KEY (id)
);

CREATE TABLE ranked
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    titulo    VARCHAR(255),
    descricao VARCHAR(255),
    ativa     BOOLEAN                                 NOT NULL,
    user_id   BIGINT,
    CONSTRAINT pk_ranked PRIMARY KEY (id)
);

CREATE TABLE users
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name               VARCHAR(255),
    email              VARCHAR(255)                            NOT NULL,
    role               VARCHAR(255),
    password           VARCHAR(255)                            NOT NULL,
    riot_id            VARCHAR(255),
    riot_summoner_name VARCHAR(255),
    riot_puuid         VARCHAR(255),
    elo                VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE coupon
    ADD CONSTRAINT uc_coupon_code UNIQUE (code);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE assinatura
    ADD CONSTRAINT FK_ASSINATURA_ON_USUARIO FOREIGN KEY (usuario_id) REFERENCES users (id);

ALTER TABLE coupon_usage
    ADD CONSTRAINT FK_COUPONUSAGE_ON_COUPON FOREIGN KEY (coupon_id) REFERENCES coupon (id);

ALTER TABLE coupon_usage
    ADD CONSTRAINT FK_COUPONUSAGE_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE coupon
    ADD CONSTRAINT FK_COUPON_ON_OWNER FOREIGN KEY (owner_id) REFERENCES users (id);

ALTER TABLE participante
    ADD CONSTRAINT FK_PARTICIPANTE_ON_RANKED FOREIGN KEY (ranked_id) REFERENCES ranked (id);

ALTER TABLE participante
    ADD CONSTRAINT FK_PARTICIPANTE_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE ranked
    ADD CONSTRAINT FK_RANKED_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);